heat_template_version: 2015-04-30

description: Template that installs a wordpress server and supporting MySQL database running on separate servers

# Required sub templates : lib/wordpress_networks.yaml, lib/mysql.yaml, lib/wordpress.yaml, lib/floating_ip.yaml, lib/volume_with_attachment.yaml

parameters:
  image:
    type: string
    label: Image name or ID
    description: Image to be used for server. Please use an Ubuntu based image.
    default: ubuntu-cloud-14.04
  flavor:
    type: string
    label: Flavor
    description: Type of instance (flavor) to be used on the compute instance.
    default: m1.small
  key:
    type: string
    label: Key name
    description: Name of key-pair to be installed on the compute instance.
    default: vioKey
  public_network_id:
    type: string
    label: Public network ID
    description: Public network to attach server to.
    default: c7b5445a-2e31-465e-9ec3-711aa701de76
  num_instances:
    type: number
    label: Number of wordpress instances
    description: Create a LB pool of wordpress instances
    default: 1

resources:
  network:
    type: lib/wordpress_networks.yaml
    properties:
      public_network: { get_param: public_network_id }

  the_lb:
    depends_on: network
    type: lib/edge_lb.yaml
    properties:
      lb_subnet: { get_attr: [network, wordpress_subnet_id] }

  mysql:
    type: lib/mysql.yaml
    depends_on: the_lb
    properties:
      image: { get_param: image }
      flavor: { get_param: flavor }
      key: { get_param: key }
      db_network_id: { get_attr: [network, db_net_id] }
      database_name: wordpress
      database_user: wordpress_user

  wordpress_instances:
    type: OS::Heat::ResourceGroup
    depends_on: mysql
    properties:
      count: { get_param: num_instances }
      resource_def:
        type: lib/wordpress.yaml
        properties:
          image: { get_param: image }
          flavor: { get_param: flavor }
          key: { get_param: key }
          wordpress_network_id: { get_attr: [network, wordpress_network_id] }
          wordpress_subnet_id: { get_attr: [network, wordpress_subnet_id] }
          mysql_server: { get_attr: [mysql, ip] }
          database_name: wordpress
          database_user: wordpress_user
          database_password: { get_attr: [mysql, database_password] }
          security_group: { get_attr: [network, wordpress_secgrp] }
          pool_id: { get_attr: [the_lb, pool_id] }

outputs:
  ip:
    description: The public IP address to access Wordpress.
    value: { get_attr: [the_lb, server_ip] }
